### ISSUE TITLE
add reactive operator examples

### ISSUE THREAD

**Issue by LeiYangGH** [g0t4/Rx-FileSystemWatcher#6]
this library is named rx-, and also references rx libraries. so i assume rx operators should be easy to integrate.
but i haven't see their usages in readme nor tests.
i expect something like
```csharp
watcher.Changed.someoperator.Subscribe
```
in which someoperator can be `Buffer`, `Defer`, `Distinct` and so on.

**Comment by g0t4** [comment]
You might need to import a namespace to find extension methods from Rx.

**Comment by fbarresi** [comment]
Hello @LeiYangGH, 
I followed your question, because I subscribed this project.

It feels disturbing to me to read between the lines you are upset because you were unable to find out the usage of the library.

Please remember that @g0t4 and all other developers that publish open-source software here share not only their know-how, but also their time and passion in what they do. It might be unperfect, unfinished or not well documented, but it's still a gift.

So for the future I hope you can remember the following rule of good conduct:
- Be grateful (this is open source portal, not a software shop) 
- Try out before rising an issue (I'm sure if you check out a project you will know more than at the homepage) 
- (optional) If you think it should be made better and you know how: contribute

I trust you understand me.

Best regards,
FB

**Comment by LeiYangGH** [comment]
i think @g0t4 is correct, adding namespace referencing can solve.
@fbarresi i think if you have time to write so long comments, it is better to improve the readme.
raising issue is a way to contribute, isn't it? i had download the code and looked the source, otherwise how could i say i didn't find those in the **tests**?
